default: &default
  adapter: mysql2
  database: zw_dev
  encoding: utf8
  username: root
  password: FaRt17227797
  #socket: /var/run/mysqld/mysqld.sock

test:
  <<: *default
  database: zw_test

production:
  <<: *default
  database: zw_prod

development:
  <<: *default
  pool: 8